### PR TITLE
Fixed 'redux-logger-example' production build

### PR DESCRIPTION
**Pull request by toxickg**
Disabled 'react-transform-hmr' for production environment (as it's supposed to).

### CODE REVIEW

**Comment by toxickg** [comment]
http://fcomb.github.io/redux-logger/ doesn't work after the latest merge 'cause `react-transform-hmr` must now be disabled for production builds. The update of dependencies provoked this failure.

**Comment by oliviertassinari** [comment]
related to https://github.com/fcomb/redux-logger/issues/44

**Comment by theaqua** [comment]
FIxed (https://github.com/fcomb/redux-logger/commit/ee2d7826b11a1b32511897e00a33252c1d9d2f8d). 
I saw it before your PR and fought yesterday, but forgot about `NODE_ENV=production`. Thanks for fast reaction!

**Comment by toxickg** [comment]
Oh, great. Thanks for adding me!

**Pull request closed without merging**
