### PR TITLE
Fix expected identifier error in IE8

### PR DESCRIPTION
**Pull request by kwarr128**
Fix for https://github.com/fcomb/redux-logger/issues/110

Mirroring same solution from redux-thunk project:
https://github.com/gaearon/redux-thunk/issues/45
https://github.com/gaearon/redux-thunk/commit/00f7fdb9b41e7445941692bc9c808f3769be22bd?diff=unified

### CODE REVIEW

**Comment by theaqua** [comment]
Thanks!

**Comment by SimenB** [comment]
@theaqua Could you publish a new version with this?

**Comment by theaqua** [comment]
@SimenB yes, of course. I published 2.3.2 with this fix.

**Comment by SimenB** [comment]
Great, thanks!

**Pull request merged**
