### PR TITLE
fix logger order

### PR DESCRIPTION
**Pull request by jetzhliu**
When redux dispatch an action, after calling the reducer, the listeners
will be called. If the listener dispatch a new action, redux allow it,
but the order of the log will in reverse.
this PR fix the order in that case.

### CODE REVIEW

**Comment by theaqua** [comment]
Can you make a demo, please?

**Comment by jetzhliu** [comment]
OK, but it may take some time because of my bad network~~
You can also add a listener to the store, and dispatch a new action in some case, then the later action will log first. It may be a bad pattern, but some 3rd lib do that...

**Comment by theaqua** [comment]
I'll try tomorrow.

**Comment by hon2a** [comment]
I can confirm the issue is real. Listeners subscribed to redux store are executed synchronously, so running `next(action)` inside the logger actually executes all subscribed listeners. If any of them dispatch any other action in reaction to the updated state, this other action is dispatched on top of the current stack and it is therefore logged before the original action.

**Comment by bitfrost** [comment]
We are also seeing this, @theaqua  would you like a demo still? If so I can put one together.

**Comment by theaqua** [comment]
@bitfrost yes please. I don't have enough time :(

**Comment by bitfrost** [comment]
Here you go:
https://github.com/bitfrost/logging-in-wrong-order

https://github.com/bitfrost/logging-in-wrong-order/blob/master/index.es6

open index.html and view the logger output  and compile it with console.log output from the 1 reducer.

**Comment by theaqua** [comment]
Thanks, @bitfrost!

Hey, @jetzhliu, can you fix merge conflict, please? I'll merge ASAP.

**Comment by jetzhliu** [comment]
thank you very mush @bitfrost & @theaqua . I will merge conflict now.

**Comment by jetzhliu** [comment]
I has merged conflict.
but I has one question: is it necessary to print preview state?

**Comment by theaqua** [comment]
@jetzhliu of course :)

Thanks!

**Comment by theaqua** [comment]
Released in [2.4.0](https://github.com/fcomb/redux-logger/releases/tag/2.4.0).

**Pull request merged**
