### PR TITLE
Pinned all dependencies

### PR DESCRIPTION
**Pull request by theaqua**
:wave: Hello!

We’re all trying to keep our software up to date, yet stable at the same time.

This is the first in a series of automatic PRs to help you achieve this goal. It pins all of the dependencies in your `package.json`, so you have complete control over the exact state of your software.

From now on you’ll receive PRs whenever one of your dependencies updates – in real time. This way you get all the benefits of up-to-date dependencies, while having them pinned at the same time. This means:

- No more surprises because some of your dependencies didn’t follow [SemVer](http://semver.org/). Your software is always in a state you know about, regardless of _when_ someone does `$ npm install`.
- If you have continuous integration set up for this repo, it’ll run automatically. Ideally, it will pass and you'll stay up to date with the press of a button. If the updated dependency _does_ break your software, it won’t affect your users, because their dependencies are still pinned to the working state.
- You can immediately identify which dependency updates break your software, because each one is tested in isolation. You’ll also have a branch ready to work on, so adapting to new APIs is way faster.

Merge this PR and you’ll have up-to-date software without the headaches :sparkles:

---

This pull request was created by [greenkeeper.io](http://greenkeeper.io/).
It keeps your software, up to date, all the time.

<sub>
Tired of seeing this sponsor message? Upgrade to the supporter plan!
You'll also get your pull requests faster :zap:
</sub>

### CODE REVIEW

**Comment by epeli** [comment]
Isn't this really bad for the client side? npm deduplicates the dependencies which are compatible with each others. Now if you have two libs in a project doing this you'll get two copies of their shared dependencies even differ even slightly ex. `1.0.1` and `1.0.0`.

**Comment by gaearon** [comment]
These are `devDependencies` tho. But I'm also curious about this.

**Comment by theaqua** [comment]
@epeli I have 7 opensource libraries which depends on other packages. I testing greenkeeper because it can be useful — now I see PR and don't need to run `npm-check-updates` in each project. Of course, I'll manually check each PR, but I want automate it. Why not?

**Comment by theaqua** [comment]
@epeli in my projects I try keep dependencies up-to-date, because on other side it can be painful after some time. I think if anyone updates `redux-logger` from 1.0.8 to 1.0.9, he updates other packages too.

**Comment by epeli** [comment]
That works as long as every lib maintainer doing this is actively updating their deps. Even if one falls out users will start getting duplicate deps. Could some of the greenkeeper guys comment on this, @theaqua ?

> These are devDependencies tho. But I'm also curious about this.

Yeah, in this case it's not so bad.

**Comment by boennemann** [comment]
Hey y'all, Greenkeeper dev here :wave: 

the answer to this question is manifold.

First of all we hope that Greenkeeper will have an impact on the entire ecosystem so that packages are just up-to-date everywhere – unless they're yet incompatible.

Secondly, we will roll out other modes for Greenkeeper soon, so you can also decide to still use ~, ^, or get PRs even if the new version satisfies the current range. That way you could keep ranges and still get PRs for every update. These are not intended to be merged, you just see if they still pass and close them. If they fail though, you immediately know your dependency broke and can use the branch to add a fix.

And last but not least we will roll out shrinkwrap support, so you can globally keep dependencies up-to-date and potentially get even more deduping potential.

Best,
Stephan

**Comment by theaqua** [comment]
@boennemann excuse me, but can greenkeeper send PRs from it's own account, not mine?

**Comment by boennemann** [comment]
@theaqua Unfortunately that isn't possible. It is against the API terms to send automated PRs from another account and we have to use the individual tokens, so we can remain under the rate limit for everyone to make sure PRs arrive in time.

We'd love to have some way of sending you the PR in another way, e.g. a delegate content creation API by GitHub, but such a thing is currently not available.

One way would to just signup with a bot account and reenabling the repo from there.

**Comment by theaqua** [comment]
@boennemann https://github.com/fcomb/fcomb/pull/7 ?

**Comment by boennemann** [comment]
@theaqua I know that they're doing it, but we don't want to put our service at risk of being shutdown.
Also we'll soon be sending several thousand PRs a day, which, in contrast to gitter, will bring us to the limits of a single account's rate limit very quickly.

We're trying to figure out a solution with GitHub, but for now this how we _have_ to do it – even though we don't like to do it this way. If you know of any special terms for Gitter, please let us know (E.g. there page isn't available: https://github.com/gitter-badger).  

Thanks for understanding.

**Comment by theaqua** [comment]
@boennemann I see. Hope you'll find solution with GitHub team ✊

**Comment by boennemann** [comment]
@theaqua @gaearon @epeli Regarding version ranges: You can now add version ranges to your dependencies again and we will treat them right.

For new versions inside the existing range you’ll get pull-requests only if the update breaks your build. We are doing this by only creating the branch and then waiting for results from your CI. If it passes the branch gets deleted again, if it fails however the pull requests gets opened, because it should definitely have your attention.

```diff
-  "underscore": "^1.6.0"
+  "underscore": "^1.7.0"
```

When a new version is outside of your existing range you’ll just get the pull request right away.

```diff
-  "lodash": "^3.0.0"
+  "lodash": "^4.0.0"
```

You can now define the level of "noise" per dependency by using "^", "~", or pin.
We hope you like this change and would be very happy to get your feedback on this.

@theaqua We found a solution with GitHub and we're now sending pull-requests from our account.

Best,
Stephan

**Comment by epeli** [comment]
> You can now define the level of "noise" per dependency by using "^", "~", or pin.

This sounds great! I hope you do warn about the consequences of the pin option for npm's ability to  dedupe modules for browser bundles in your docs.

**Comment by theaqua** [comment]
@boennemann it's awesome, thanks!

**Pull request merged**
