### PR TITLE
Add logTransitions option to disable printing stating transitions

### LINKED ISSUE #94: Option to only log actions
It would have been great with an option to turn off logging of states, and to only log actions. This would be spesielle useful to follow the flow when doing test-driven development (TDD).

### PR DESCRIPTION
**Pull request by romseguy**
Fixes #94

### CODE REVIEW

**Comment by theaqua** [comment]
Only one reason why I didn't ship #54 yet: we need implement fine-grained control, not only `action`. The user must be able to disable every line: `prevState`, `action`, `nextState` or entire group like `predicate` option.

If you have an idea how to make it, please implement it and I'll merge.

**Comment by romseguy** [comment]
`predicate` would be able to determine whether the action should be skipped, or logged right? Maybe it would be simpler to have separate functions then, even if they have the same`getState, action -> bool` signature...

**Comment by theaqua** [comment]
`predicate` already [exists](https://github.com/fcomb/redux-logger#predicate--getstate-function-action-object--boolean) :)

We need a new option which resolves behaviour of showing `nextState`, `action` and `prevState`.

**Comment by theaqua** [comment]
fixed by #130

**Pull request closed without merging**
