### PR TITLE
Fixed Immutable logger example

### PR DESCRIPTION
**Pull request by dreampulse**
The example is not working.
However, this is even simpler

### CODE REVIEW

**Comment by theaqua** [comment]
Thanks!

**Comment by RoberMac** [comment]
this PR is not work.

**Comment by theaqua** [comment]
@RoberMac details

**Comment by RoberMac** [comment]
@theaqua 
screen shot 2016-04-02 at 5 19 50 pm

**Comment by theaqua** [comment]
cc @dreampulse

**Comment by jakegavin** [comment]
I also just ran into the example code not working. 

The new example code merged into the readme by this PR assumes that your state is a subclass of `Immutable.Iterable`. If you use redux's `combineReducers`, your state is likely a [plain old javascript object](https://github.com/reactjs/redux/blob/master/src/combineReducers.js#L124) and thus this new example code wont work with it.

Looks like the original example code works if you have state as a POJO

@theaqua I'd propose either reverting this PR since its my understanding that most non-trivial redux apps will be using `combineReducers` (but I'm not sure how accurate of a statement that is) or modifying the readme to mention both approaches. I'd be happy to write a little something up if you'd prefer the latter.

**Comment by theaqua** [comment]
Thanks, done.

**Pull request merged**
